ESEC2008-01P
172.18.115.147 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.25.69.65 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.24.156.51 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
Traceback (most recent call last):
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7ff681401790>, 'Connection to 10.151.27.1 timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/j/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.151.27.1', port=8086): Max retries exceeded with url: /info (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff681401790>, 'Connection to 10.151.27.1 timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j/EsecUnitAnormalyDetection/RegistDevice/main.py", line 50, in <module>
    postData()
  File "/home/j/EsecUnitAnormalyDetection/RegistDevice/main.py", line 45, in postData
    response = requests.request("POST", url, headers=headers, data=payload,timeout=5)
  File "/home/j/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/j/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/j/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/j/.local/lib/python3.8/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='10.151.27.1', port=8086): Max retries exceeded with url: /info (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff681401790>, 'Connection to 10.151.27.1 timed out. (connect timeout=5)'))
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
ESEC2008-01P
172.21.252.116 00:15:5D:1E:67:03
{"msg":"Updated"}
